version = 1

[envs.fish]
channels = ["conda-forge"]
dependencies = { fish = "*" }
exposed = { fish = "fish", fish_indent = "fish_indent", fish_key_reader = "fish_key_reader" }

[envs.zoxide]
channels = ["conda-forge"]
dependencies = { zoxide = "*" }
exposed = { zoxide = "zoxide" }

[envs.fzf]
channels = ["conda-forge"]
dependencies = { fzf = "*" }
exposed = { fzf = "fzf" }

[envs.yazi]
channels = ["conda-forge"]
dependencies = { yazi = "*" }
exposed = { ya = "ya", yazi = "yazi" }

[envs.go-ghq]
channels = ["conda-forge"]
dependencies = { go-ghq = "*" }
exposed = { ghq = "ghq" }

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.python]
channels = ["conda-forge"]
dependencies = { python = "*", "pip" = "*"  }
exposed = { idle3 = "idle3", "idle3.14" = "idle3.14", pydoc = "pydoc", pydoc3 = "pydoc3", "pydoc3.14" = "pydoc3.14", python = "python", python3 = "python3", python3-config = "python3-config", "python3.1" = "python3.1", "python3.14" = "python3.14", "python3.14-config" = "python3.14-config", "pip" = "pip", "pip3" = "pip"}

[envs.dust]
channels = ["conda-forge"]
dependencies = { dust = "*" }
exposed = { dust = "dust" }

[envs.zip]
channels = ["conda-forge"]
dependencies = { zip = "*" }
exposed = { zip = "zip", zipcloak = "zipcloak", zipnote = "zipnote", zipsplit = "zipsplit" }

[envs.unzip]
channels = ["conda-forge"]
dependencies = { unzip = "*" }
exposed = { funzip = "funzip", unzip = "unzip", unzipsfx = "unzipsfx", zipgrep = "zipgrep", zipinfo = "zipinfo" }

[envs.ffmpeg]
channels = ["conda-forge"]
dependencies = { ffmpeg = "*" }
exposed = { ffmpeg = "ffmpeg", ffplay = "ffplay", ffprobe = "ffprobe" }

[envs.clang]
channels = ["conda-forge"]
dependencies = { clang = "*" }
exposed = { clang = "clang", clang-cl = "clang-cl", clang-cpp = "clang-cpp" }

[envs.xh]
channels = ["conda-forge"]
dependencies = { xh = "*" }
exposed = { xh = "xh", xhs = "xhs" }

[envs.jq]
channels = ["conda-forge"]
dependencies = { jq = "*" }
exposed = { jq = "jq" }

[envs.sshs]
channels = ["conda-forge"]
dependencies = { sshs = "*" }
exposed = { sshs = "sshs" }

[envs.pueue]
channels = ["conda-forge"]
dependencies = { pueue = "*" }
exposed = { pueue = "pueue", pueued = "pueued" }

[envs.hyperfine]
channels = ["conda-forge"]
dependencies = { hyperfine = "*" }
exposed = { hyperfine = "hyperfine" }

[envs.dua-cli]
channels = ["conda-forge"]
dependencies = { dua-cli = "*" }
exposed = { dua = "dua" }

[envs.diskonaut]
channels = ["conda-forge"]
dependencies = { diskonaut = "*" }
exposed = { diskonaut = "diskonaut" }

[envs.nvim]
channels = ["conda-forge"]
dependencies = { nvim = "*" }
exposed = { nvim = "nvim" }

[envs.nodejs]
channels = ["conda-forge"]
dependencies = { nodejs = "*" }
exposed = { node = "node", npm = "npm", npx = "npx" }

[envs.yarn]
channels = ["conda-forge"]
dependencies = { yarn = "*" }
exposed = { yarn = "yarn", "yarn.cmd" = "yarn.cmd", "yarn.js" = "yarn.js", "yarn.ps1" = "yarn.ps1" }

[envs.tldr]
channels = ["conda-forge"]
dependencies = { tldr = "*" }
exposed = { tldr = "tldr" }

[envs.tree]
channels = ["conda-forge"]
dependencies = { tree = "*" }
exposed = { tree = "tree" }

[envs.git]
channels = ["conda-forge"]
dependencies = { git = "*" }
exposed = { git = "git", git-credential-osxkeychain = "git-credential-osxkeychain", git-cvsserver = "git-cvsserver", git-receive-pack = "git-receive-pack", git-shell = "git-shell", git-upload-archive = "git-upload-archive", git-upload-pack = "git-upload-pack", gitk = "gitk", scalar = "scalar" }

[envs.jupyter]
channels = ["conda-forge"]
dependencies = { jupyter = "*" }
exposed = { jupyter = "jupyter" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.git-delta]
channels = ["conda-forge"]
dependencies = { git-delta = "*" }
exposed = { delta = "delta" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.parallel]
channels = ["conda-forge"]
dependencies = { parallel = "*" }
exposed = { env_parallel = "env_parallel", "env_parallel.ash" = "env_parallel.ash", "env_parallel.dash" = "env_parallel.dash", "env_parallel.mksh" = "env_parallel.mksh", "env_parallel.pdksh" = "env_parallel.pdksh", niceload = "niceload", parallel = "parallel", parcat = "parcat", parset = "parset", parsort = "parsort", sem = "sem", sql = "sql" }

[envs.ninja]
channels = ["conda-forge"]
dependencies = { ninja = "*" }
exposed = { ninja = "ninja" }

[envs.htop]
channels = ["conda-forge"]
dependencies = { htop = "*" }
exposed = { htop = "htop" }

[envs.git-lfs]
channels = ["conda-forge"]
dependencies = { git-lfs = "*" }
exposed = { git-lfs = "git-lfs" }

[envs.nvtop]
channels = ["conda-forge"]
dependencies = { nvtop = "*" }
exposed = { nvtop = "nvtop" }

[envs.btop]
channels = ["conda-forge"]
dependencies = { btop = "*" }
exposed = { btop = "btop" }

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }
