version = 1

[envs.fish]
channels = ["conda-forge"]
dependencies = { fish = "*" }
exposed = { fish = "fish", fish_indent = "fish_indent", fish_key_reader = "fish_key_reader" }

[envs.zoxide]
channels = ["conda-forge"]
dependencies = { zoxide = "*" }
exposed = { zoxide = "zoxide" }

[envs.fzf]
channels = ["conda-forge"]
dependencies = { fzf = "*" }
exposed = { fzf = "fzf" }

[envs.yazi]
channels = ["conda-forge"]
dependencies = { yazi = "*" }
exposed = { ya = "ya", yazi = "yazi" }

[envs.go-ghq]
channels = ["conda-forge"]
dependencies = { go-ghq = "*" }
exposed = { ghq = "ghq" }

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.conda]
channels = ["conda-forge"]
dependencies = { conda = "*" }
exposed = { activate = "activate", conda = "conda", conda-env = "conda-env", deactivate = "deactivate" }

[envs.zellij]
channels = ["conda-forge"]
dependencies = { zellij = "*" }
exposed = { zellij = "zellij" }

[envs.python]
channels = ["conda-forge"]
dependencies = { python = "*", "pip" = "*"  }
exposed = { idle3 = "idle3", "idle3.14" = "idle3.14", pydoc = "pydoc", pydoc3 = "pydoc3", "pydoc3.14" = "pydoc3.14", python = "python", python3 = "python3", python3-config = "python3-config", "python3.1" = "python3.1", "python3.14" = "python3.14", "python3.14-config" = "python3.14-config", "pip" = "pip", "pip3" = "pip"}

[envs.dust]
channels = ["conda-forge"]
dependencies = { dust = "*" }
exposed = { dust = "dust" }

[envs.zip]
channels = ["conda-forge"]
dependencies = { zip = "*" }
exposed = { zip = "zip", zipcloak = "zipcloak", zipnote = "zipnote", zipsplit = "zipsplit" }

[envs.unzip]
channels = ["conda-forge"]
dependencies = { unzip = "*" }
exposed = { funzip = "funzip", unzip = "unzip", unzipsfx = "unzipsfx", zipgrep = "zipgrep", zipinfo = "zipinfo" }

[envs.ffmpeg]
channels = ["conda-forge"]
dependencies = { ffmpeg = "*" }
exposed = { ffmpeg = "ffmpeg", ffplay = "ffplay", ffprobe = "ffprobe" }

[envs.clang]
channels = ["conda-forge"]
dependencies = { clang = "*" }
exposed = { clang = "clang", clang-cl = "clang-cl", clang-cpp = "clang-cpp" }
