add_newline=false
[time]
disabled=false
format='[$time]($style) '
time_format='%F %T'
[directory]
truncation_symbol = 'â€¦/'
truncate_to_repo=false
[status]
symbol = ""
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
